---
name: LitmusGO-CI
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
  AWS_Experiment_Test:

      #Install and configure a k3s cluster
      - name: Installing Prerequisites (K3S Cluster)
        env: 
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        run: |
          curl -sfL https://get.k3s.io | sh -s - --docker --write-kubeconfig-mode 664
          kubectl wait node --all --for condition=ready --timeout=90s
          kubectl get nodes
          
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: Litmus Infra Setup
        run: make build-litmus

      - name: create kubernetes secret for aws experiment
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: cloud-secret
            namespace: default
          type: Opaque
          stringData:
            cloud_config.yml: |-
              [default]
              aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: us-west-1
          
          
      - name: Creating the EC2 instance to target
        run: |
          aws ec2 run-instances --image-id ami-0d382e80be7ffdae5 --count 2 --instance-type t2.nano \
          --key-name udit-litmus-e2e --security-group-ids sg-06925d6218d07e795 --subnet-id subnet-9c2ba8fa \
          --region us-west-1
          
      - name: Get the secrets
        run: kubectl get secrets
      
